# Generated by Django 2.1.15 on 2020-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200520_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_like',
            field=models.CharField(default='00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=200),
        ),
    ]
