# Generated by Django 2.1.15 on 2020-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_user_work_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_entered',
            field=models.BooleanField(default=False),
        ),
    ]
