# Generated by Django 2.1.15 on 2020-06-03 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_user_data_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_recommend',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=5),
        ),
    ]
