# Generated by Django 2.1.15 on 2020-06-07 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_user_work_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_evaluated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='work_evaluation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=20), default=list, size=100000),
        ),
    ]
