# Generated by Django 2.1.15 on 2020-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmppass',
            field=models.TextField(default=None, null=True),
        ),
    ]
