# Generated by Django 2.1.15 on 2020-05-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('like_average', models.FloatField(default=0)),
                ('joy', models.FloatField(default=0)),
                ('anger', models.FloatField(default=0)),
                ('sadness', models.FloatField(default=0)),
                ('fun', models.FloatField(default=0)),
                ('tech_constitution', models.FloatField(default=0)),
                ('tech_story', models.FloatField(default=0)),
                ('tech_character', models.FloatField(default=0)),
                ('tech_speech', models.FloatField(default=0)),
                ('tech_picture', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='works',
        ),
    ]
