# Generated by Django 2.1.15 on 2020-05-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0002_auto_20200517_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='like_average',
            new_name='like',
        ),
        migrations.AddField(
            model_name='work',
            name='num_of_data',
            field=models.IntegerField(default=0),
        ),
    ]
