# Generated by Django 2.1.15 on 2020-05-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0003_auto_20200518_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='fun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='joy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='sadness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='tech_character',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='tech_constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='tech_picture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='tech_speech',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='tech_story',
            field=models.IntegerField(default=0),
        ),
    ]
