# Generated by Django 2.1.15 on 2020-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0004_auto_20200518_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
