# Generated by Django 2.1.15 on 2020-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0010_auto_20200602_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedwork',
            name='genre',
            field=models.IntegerField(default=1),
        ),
    ]
