# Generated by Django 2.1.15 on 2020-06-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0012_auto_20200603_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedwork',
            name='tech_acting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addedwork',
            name='tech_audio',
            field=models.IntegerField(default=0),
        ),
    ]
