# Generated by Django 2.1.15 on 2020-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0014_auto_20200605_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
