# Generated by Django 2.1.15 on 2020-06-07 16:13
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'mkdata/fixture/works_ver07.json', app_label='mkdata')


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0017_auto_20200608_0023'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
