# Generated by Django 2.1.15 on 2020-06-08 15:57
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'mkdata/fixture/works_ver08.json', app_label='mkdata')
    call_command('loaddata', 'mkdata/fixture/works_ver09.json', app_label='mkdata')
    call_command('loaddata', 'mkdata/fixture/jp_movies_ver00.json', app_label='mkdata')


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0018_auto_20200608_0113'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
