# Generated by Django 2.1.15 on 2020-06-08 17:05
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'mkdata/fixture/jp_movies_ver01.json', app_label='mkdata')


class Migration(migrations.Migration):

    dependencies = [
        ('mkdata', '0020_auto_20200609_0157'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
